# Generated by Django 4.2.18 on 2025-02-22 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_userprofile_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="default_phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be numeric", regex="^\\d+$"
                    )
                ],
            ),
        ),
    ]
