# Generated by Django 4.2.18 on 2025-02-22 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_userprofile_default_phone_number"),
        ("products", "0005_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.userprofile"
            ),
        ),
    ]
